/* Desert war RTS — the tables.

   Everything with a number in it lives here and nowhere else. The roster,
   the buildings, the gold shop and the official formulas: change them here
   and the whole war changes.

   The damage model is the real one, from the research notes:

   - every gun has a SPECIALIZATION. Against its class it hits 5x as hard;
     against everything else it hits 5x weaker. A base-killer hits a flak
     tower like thunder and a tank like a whip.
   - "big vehicle" means armour of 1500 or more. "big aircraft" means
     armour of 2500 or more. The thresholds are the whole definition.
   - some guns DOUBLE or TRIPLE their range when they engage their class,
     and a few of those only while the target is moving or firing.
   - flaks and command centres are HARD targets: the more guns shoot one,
     the less each shot does. A hundred guns beat three times the damage
     of ten, not ten times. Swarming a flak tower is how cheap units get
     wasted.
   - fuel is not a build cost, it is the road: a moving army drinks from
     your map's fuel pool, and an empty pool is a frozen army. */
(() => {
  "use strict";
  const ZS = (window.ZS = window.ZS || {});
  const R = (ZS.RTS = ZS.RTS || {});

  /* =======================================================================
     RESOURCES
     ======================================================================= */

  R.RES = [
    {
      key: "concrete",
      name: "Concrete",
      short: "CON",
      ink: [150, 146, 132],
      coef: 1000, // storage per sqrt(plant count x 1000)
      home: 1000000, // home base adds this much room
      second: 750000, // a second base on the home ground adds more
    },
    {
      key: "steel",
      name: "Steel",
      short: "STL",
      ink: [110, 118, 126],
      coef: 300,
      home: 500000,
      second: 1000000,
    },
    {
      key: "alu",
      name: "Aluminium",
      short: "ALU",
      ink: [158, 162, 168],
      coef: 100,
      home: 250000,
      second: 500000,
    },
    {
      key: "fuel",
      name: "Fuel",
      short: "FUE",
      ink: [166, 122, 58],
      coef: 1000,
      home: 1000000,
      second: 750000,
    },
  ];
  R.RES_KEYS = R.RES.map((r) => r.key);
  R.RES_NAME = {};
  R.RES_SHORT = {};
  R.RES_INK = {};
  R.RES.forEach((r) => {
    R.RES_NAME[r.key] = r.name;
    R.RES_SHORT[r.key] = r.short;
    R.RES_INK[r.key] = R.rgb(r.ink);
  });
  // gold is not a store; it is a purse
  R.GOLD = { name: "Gold", short: "GOLD", ink: [176, 140, 44] };
  R.RES_GOLD_INK = R.rgb(R.GOLD.ink);

  /* =======================================================================
     THE OFFICIAL FORMULAS
     ======================================================================= */

  // the more settlements you hold, the less efficient each one is.
  // total output still grows — as sqrt(n) — but nine bases give three
  // times the steel, not nine times.
  R.productivity = function (n) {
    n = Math.max(1, n);
    return Math.sqrt(n) / n;
  };

  // storage: every plant of a kind raises the ceiling a little less than
  // the one before, and the home ground carries the rest.
  R.storageOf = function (resKey, plants, sites) {
    const r = R.RES.find((x) => x.key === resKey);
    let cap = Math.round(Math.sqrt(Math.max(0, plants) * 1000)) * r.coef;
    cap += r.home;
    if (sites >= 2) cap += r.second;
    return cap;
  };

  // how many squads the company may command. One base is five and a
  // little; every ten bases earn another ten, and the home flag adds two.
  R.groupLimit = function (sites) {
    return Math.pow(Math.max(1, sites) / 10, 0.5) * 10 + 2;
  };

  // ENERGY POINTS. Every level of every plant costs; every flak costs.
  // Start with 1000, a power plant buys 100 more, fifteen of them is the
  // end of the line.
  R.EP_START = 1000;
  R.EP_POWERPLANT = 100;
  R.EP_MAX_PLANTS = 15;
  R.EP_TOLERANCE = 99; // you may overdraw this much and still produce

  // MILITARY POINTS. Every unit stands in the book, built or being built.
  R.MP_START = 1000;
  R.MP_TOLERANCE = 99;

  // bases: one home, nine more, and a command base buys a tenth.
  R.BASE_START = 10;
  R.BASE_MAX_COMMAND = 3;

  // factory levels. Twelve without an extension; the extension buys the
  // last four (fifteen for the refinery, which runs a little hot).
  R.LVL_BASE = 12;
  R.LVL_MAX = { concrete: 16, steel: 16, alu: 16, oil: 15 };
  // each level costs a little more and makes a lot more
  R.LVL_COST_MUL = 1.32;
  R.LVL_TIME_MUL = 1.17;
  R.LVL_RATE_MUL = 1.52;
  R.LVL_HP_MUL = 1.26;
  // energy a level of a plant costs, per plant kind
  R.EP_PER_LVL = { concrete: 5, steel: 7, alu: 9, fuel: 11 };
  R.EP_FLAK = 9;

  // the hard-target rule: n guns on one flak tower do n^0.48 of one gun.
  R.hardScale = function (n) {
    if (n <= 1) return 1;
    return Math.pow(n, -0.52);
  };

  // armour. The old pen-vs-armour gap, softened: plate matters, it does
  // not wall you off. The class thresholds do the real dividing.
  R.armorMul = function (pen, arm) {
    return R.clamp(1 + (pen - arm) * 0.0009, 0.55, 1.5);
  };

  // the specialization verdict: 5 against the class, 1/5 against the rest.
  R.SPEC_MUL = 5;
  R.SPEC_OFF = 0.2;
  R.BIG_VEH_ARM = 1500; // armour this high is a "big vehicle"
  R.BIG_AIR_ARM = 2500; // armour this high is a "big aircraft"

  /* =======================================================================
     BASE TYPES
     A site is born as something and stays that something. You cannot
     choose where the airfield falls; you conquer it or you do not have
     planes.
       home   the player's home ground: the exclusive trucks, the gold
     faucets, everything a company needs to begin
       tank   battle tanks, assault guns, flak cars
       air    fixed wing
       copter rotary wing — and, as if to prove there are no rules, the
     three heaviest things on the map
       naval  the shipyard, on the water
       train  the railyard, on the track
     ======================================================================= */

  R.BASE_TYPES = {
    home: {
      name: "Home base",
      marker: "H",
      mil: "works",
      desc: "The company's own ground. Builds ground forces and the gold trucks.",
    },
    tank: { name: "Tank base", marker: "T", mil: "works", desc: "Builds the vehicle works." },
    air: {
      name: "Air base",
      marker: "A",
      mil: "airfield",
      desc: "Builds the airfield. Fixed wing only.",
    },
    copter: {
      name: "Rotor base",
      marker: "R",
      mil: "heli",
      desc: "Builds the rotor pad. Rotary wing — and the heaviest vehicles on the map.",
    },
    naval: {
      name: "Naval base",
      marker: "N",
      mil: "shipyard",
      desc: "Builds the shipyard. Must be on the water.",
    },
    train: {
      name: "Rail base",
      marker: "L",
      mil: "trainyard",
      desc: "Builds the railyard. Armoured trains, on the track only.",
    },
  };

  /* =======================================================================
     UNITS
     Every card carries the full research table:
       steel/alu  the cost, straight from the data sheets
       dmg/arm/rng the gun: damage, armour, range (the sheet's 5..18,
                   scaled to the world by R.RNG_SCALE)
       fuel       what a moving second of it drinks from the pool
       mp         the points it stands in the military book
       grp        how many of it ride in one squad
       speed      world units per second
       sight      world units
       time       seconds on the line
       spec       the specialization (see the class list below)
       rm         range multiplier vs the class (2 or 3), rmMove: only
                  while the class target moves or fires
       shape      which drawing routine gets the honour
       build      which building (and base type) may make it
     ======================================================================= */

  R.RNG_SCALE = 42; // the sheet's range units, in world distance
  R.FUEL_BURN = 0.08; // the sheet's fuel figure, in pool units per second

  // the class vocabulary, read off a target
  R.classOf = function (o) {
    if (!o || !o.def) return "bld";
    if (o.kind === "b") return "bld";
    const d = o.def;
    if (d.cls === "air") return d.shape === "heli" ? "copter" : "plane";
    if (d.cls === "sea") return "boat";
    if (d.train) return "train";
    return d.cls; // inf | soft | arm
  };

  // does this gun love this target?
  R.specMatch = function (spec, tgt) {
    if (!spec) return false;
    const c = R.classOf(tgt);
    const arm = tgt.def ? tgt.def.arm || 0 : 0;
    switch (spec) {
      case "base":
        return c === "bld";
      case "vehicle":
        return c === "arm" || c === "soft" || c === "inf";
      case "bigveh":
        return (c === "arm" || c === "soft") && arm >= R.BIG_VEH_ARM;
      case "weakveh":
        return (c === "arm" || c === "soft" || c === "inf") && arm < 120;
      case "vehboat":
        return c === "arm" || c === "soft" || c === "boat";
      case "vehtrain":
        return c === "arm" || c === "soft" || c === "train";
      case "baunit":
        return tgt.def && tgt.def.spec === "base";
      case "air":
        return c === "copter" || c === "plane";
      case "bigair":
        return (c === "copter" || c === "plane") && arm >= R.BIG_AIR_ARM;
      case "copter":
        return c === "copter";
      case "boat":
        return c === "boat";
      case "boattrain":
        return c === "boat" || c === "train";
      case "train":
        return c === "train";
    }
    return false;
  };

  const R_ = function (r) {
    return Math.round(r * R.RNG_SCALE);
  };

  const U = {
    /* ---------------- vehicles ---------------- */
    apc: {
      name: "Conquest Truck",
      short: "CQT",
      cls: "soft",
      shape: "truck",
      hp: 520,
      arm: 3,
      speed: 75,
      sight: 330,
      fuel: 20,
      mp: 15,
      grp: 5,
      time: 14,
      cost: { steel: 45000, alu: 5000 },
      build: "works",
      capture: true,
      unarmed: true,
      role: "Takes ground. Drive it onto an open settlement and hold it.",
    },
    mgmc: {
      name: "M-16 Gun Car",
      short: "MG16",
      cls: "soft",
      shape: "car",
      hp: 540,
      arm: 7,
      speed: 90,
      sight: 380,
      fuel: 10,
      mp: 15,
      grp: 9,
      time: 14,
      cost: { steel: 45000, alu: 25000 },
      build: "works",
      spec: "air",
      rm: 2,
      w: {
        dmg: 200,
        rof: 4.2,
        range: R_(5),
        pen: 12,
        speed: 1300,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "Cheap sky. An army without it is a bomber's buffet.",
    },
    lynx: {
      name: "Lynx V2",
      short: "LYNX",
      cls: "soft",
      shape: "tank",
      small: 1,
      hp: 620,
      arm: 15,
      speed: 80,
      sight: 420,
      fuel: 15,
      mp: 15,
      grp: 47,
      time: 9,
      cost: { steel: 35000, alu: 5000 },
      build: "works",
      homeOnly: true,
      w: { dmg: 100, rof: 1.6, range: R_(8), pen: 8, speed: 1200, kind: "bullet" },
      role: "The cheap scout tank of the home ground. Forty-seven to a squad.",
    },
    runner: {
      name: "Dune Runner",
      short: "DRUN",
      cls: "soft",
      shape: "car",
      hp: 560,
      arm: 7,
      speed: 110,
      sight: 420,
      fuel: 5,
      mp: 15,
      grp: 12,
      time: 12,
      cost: { steel: 65000, alu: 25000 },
      build: "works",
      homeOnly: true,
      fast: true,
      rm: 2,
      w: { dmg: 500, rof: 0.8, range: R_(8), pen: 18, speed: 900, kind: "rocket", splash: 34 },
      role: "Fast, and its rockets outrange the jeeps that carry them.",
    },
    volna: {
      name: "Volna MLRS",
      short: "VOLN",
      cls: "soft",
      shape: "artillery",
      hp: 700,
      arm: 10,
      speed: 55,
      sight: 420,
      fuel: 25,
      mp: 40,
      grp: 3,
      time: 60,
      cost: { steel: 850000, alu: 750000 },
      build: "works",
      rm: 3,
      noAA: true,
      w: {
        dmg: 5000,
        rof: 0.5,
        range: R_(10),
        pen: 40,
        speed: 640,
        kind: "rocket",
        splash: 80,
        arc: true,
      },
      role: "A curtain of rockets. Triple range, no answer to the sky.",
    },
    sheriff: {
      name: "Sheriff",
      short: "SHER",
      cls: "arm",
      shape: "tank",
      hp: 1400,
      arm: 150,
      speed: 62,
      sight: 420,
      fuel: 50,
      mp: 30,
      grp: 5,
      time: 40,
      cost: { steel: 450000, alu: 200000 },
      build: "works",
      w: { dmg: 1500, rof: 0.7, range: R_(10), pen: 34, speed: 1000, kind: "shell", splash: 34 },
      role: "The all-rounder. The line you fight the war with.",
    },
    stormtitan: {
      name: "Stormtitan",
      short: "STRT",
      cls: "soft",
      shape: "spg",
      big: true,
      hp: 2600,
      arm: 1875,
      speed: 40,
      sight: 400,
      fuel: 75,
      mp: 90,
      grp: 1,
      time: 150,
      cost: { steel: 1970000, alu: 900000 },
      build: "works",
      spec: "base",
      noTurret: true,
      aa: true,
      ammo: 12,
      w: {
        dmg: 20000,
        rof: 0.3,
        range: R_(12),
        pen: 60,
        speed: 900,
        kind: "shell",
        splash: 100,
        aa: true,
        as: true,
      },
      role: "The siege hammer. Must stand still to fire; runs on special shells.",
    },
    mule: {
      name: "Mule Wagon",
      short: "MULE",
      cls: "soft",
      shape: "artillery",
      hp: 760,
      arm: 15,
      speed: 58,
      sight: 420,
      fuel: 30,
      mp: 30,
      grp: 4,
      time: 36,
      cost: { steel: 375000, alu: 250000 },
      build: "works",
      rm: 2,
      noAA: true,
      w: {
        dmg: 950,
        rof: 0.5,
        range: R_(10),
        pen: 30,
        speed: 620,
        kind: "rocket",
        splash: 60,
        arc: true,
      },
      role: "Road-rocket carrier. Doubles its reach, cannot look up.",
    },
    stonehammer: {
      name: "Stonehammer",
      short: "STNH",
      cls: "soft",
      shape: "tank",
      small: 1,
      hp: 800,
      arm: 30,
      speed: 60,
      sight: 420,
      fuel: 15,
      mp: 15,
      grp: 47,
      time: 9,
      cost: { steel: 95000, alu: 35000 },
      build: "works",
      spec: "base",
      w: { dmg: 250, rof: 1.4, range: R_(10), pen: 14, speed: 1100, kind: "bullet" },
      role: "The starter base-killer. Forty-seven to a squad, five times at walls.",
    },
    sandblade: {
      name: "Sand Blade",
      short: "SBLD",
      cls: "soft",
      shape: "car",
      hp: 780,
      arm: 30,
      speed: 78,
      sight: 495,
      fuel: 25,
      mp: 15,
      grp: 19,
      time: 9,
      cost: { steel: 390000, alu: 65000 },
      quota: { n: 50, mul: 0.1 }, // 50 a day at a tenth of the price, home ground only
      build: "works",
      homeOnly: true,
      spec: "base",
      w: { dmg: 1000, rof: 1.0, range: R_(10), pen: 16, speed: 1150, kind: "bullet" },
      role: "The conquest armoured car. A tenth of its price, fifty a day, home ground only.",
    },
    railbreaker: {
      name: "Railbreaker",
      short: "RLBK",
      cls: "soft",
      shape: "tank",
      small: 1,
      hp: 900,
      arm: 75,
      speed: 66,
      sight: 420,
      fuel: 35,
      mp: 25,
      grp: 6,
      time: 34,
      cost: { steel: 500000, alu: 15000 },
      build: "works",
      spec: "train",
      w: { dmg: 750, rof: 0.8, range: R_(8), pen: 26, speed: 1100, kind: "shell", splash: 30 },
      role: "Loose couplings. Trains cross its sights and stay broken.",
    },
    sandpiper: {
      name: "Sandpiper",
      short: "SDPP",
      cls: "soft",
      shape: "tank",
      small: 1,
      hp: 780,
      arm: 75,
      speed: 84,
      sight: 560,
      fuel: 45,
      mp: 20,
      grp: 7,
      time: 26,
      cost: { steel: 310000, alu: 120000 },
      build: "works",
      spec: "boat",
      rm: 3,
      w: { dmg: 150, rof: 1.2, range: R_(6), pen: 10, speed: 1100, kind: "bullet" },
      role: "Long-sight scout that can see the far shore. Ships never do.",
    },
    strider: {
      name: "Strider",
      short: "STRD",
      cls: "arm",
      shape: "tank",
      hp: 900,
      arm: 75,
      speed: 82,
      sight: 405,
      fuel: 35,
      mp: 15,
      grp: 7,
      time: 12,
      cost: { steel: 95000, alu: 55000 },
      build: "works",
      w: { dmg: 250, rof: 1.5, range: R_(8), pen: 14, speed: 1200, kind: "bullet" },
      role: "The workhorse. Seven to a squad, and it is everywhere.",
    },
    gnasher: {
      name: "Gnasher",
      short: "GNSH",
      cls: "soft",
      shape: "tank",
      small: 1,
      hp: 950,
      arm: 150,
      speed: 58,
      sight: 400,
      fuel: 50,
      mp: 25,
      grp: 6,
      time: 38,
      cost: { steel: 590000, alu: 90000 },
      build: "works",
      spec: "weakveh",
      w: { dmg: 250, rof: 1.4, range: R_(10), pen: 12, speed: 1100, kind: "bullet" },
      role: "Picks off the light things. A tank that shrugs at it is a tank.",
    },
    bulwark: {
      name: "Bulwark",
      short: "BLWK",
      cls: "arm",
      shape: "tank",
      big: true,
      hp: 3200,
      arm: 1500,
      speed: 46,
      sight: 420,
      fuel: 80,
      mp: 80,
      grp: 2,
      time: 90,
      cost: { steel: 1300000, alu: 600000 },
      build: "works",
      spec: "bigveh",
      rm: 2,
      w: { dmg: 6000, rof: 0.45, range: R_(9), pen: 55, speed: 980, kind: "shell", splash: 44 },
      role: "The big-vehicle killer. Everything armoured past 1500 is its lunch.",
    },
    huntress: {
      name: "Huntress",
      short: "HNTS",
      cls: "soft",
      shape: "td",
      hp: 1900,
      arm: 300,
      speed: 60,
      sight: 500,
      fuel: 50,
      mp: 40,
      grp: 4,
      time: 70,
      cost: { steel: 1300000, alu: 500000 },
      build: "works",
      spec: "baunit",
      rm: 2,
      w: { dmg: 800, rof: 0.8, range: R_(9), pen: 44, speed: 1500, kind: "bullet" },
      role: "Sniper of siege cars. Sees a base-killer and doubles the distance.",
    },
    riverwolf: {
      name: "Riverwolf",
      short: "RVWF",
      cls: "arm",
      shape: "tank",
      hp: 2200,
      arm: 600,
      speed: 58,
      sight: 420,
      fuel: 50,
      mp: 50,
      grp: 3,
      time: 110,
      cost: { steel: 2500000, alu: 750000 },
      build: "works",
      spec: "vehboat",
      rm: 3,
      w: { dmg: 400, rof: 0.9, range: R_(8), pen: 40, speed: 1000, kind: "shell", splash: 36 },
      role: "Trims tanks, and out-ranges the shore by three times.",
    },
    breaker1: {
      name: "Breaker I",
      short: "BRK1",
      cls: "soft",
      shape: "spg",
      hp: 1100,
      arm: 30,
      speed: 52,
      sight: 380,
      fuel: 40,
      mp: 30,
      grp: 4,
      time: 24,
      cost: { steel: 135000, alu: 105000 },
      build: "works",
      spec: "base",
      w: { dmg: 2500, rof: 0.55, range: R_(6), pen: 26, speed: 900, kind: "shell", splash: 55 },
      role: "The first assault gun. Short reach, long list of dead walls.",
    },
    breaker2: {
      name: "Breaker II",
      short: "BRK2",
      cls: "soft",
      shape: "spg",
      hp: 1350,
      arm: 50,
      speed: 54,
      sight: 400,
      fuel: 45,
      mp: 35,
      grp: 4,
      time: 36,
      cost: { steel: 390000, alu: 290000 },
      build: "works",
      spec: "base",
      w: { dmg: 1750, rof: 0.5, range: R_(10), pen: 28, speed: 900, kind: "shell", splash: 60 },
      role: "The second assault gun. Stands further back, hits the same.",
    },
    stinger: {
      name: "Stinger",
      short: "STNG",
      cls: "soft",
      shape: "spg",
      hp: 1050,
      arm: 75,
      speed: 56,
      sight: 420,
      fuel: 40,
      mp: 30,
      grp: 4,
      time: 24,
      cost: { steel: 150000, alu: 35000 },
      build: "works",
      spec: "base",
      w: {
        dmg: 1200,
        rof: 0.5,
        range: R_(10),
        pen: 24,
        speed: 620,
        kind: "shell",
        splash: 60,
        arc: true,
      },
      role: "The light howitzer. Lob it over their wall; the wall does not answer.",
    },
    mauler: {
      name: "Mauler",
      short: "MLER",
      cls: "arm",
      shape: "spg",
      big: true,
      hp: 2800,
      arm: 300,
      speed: 44,
      sight: 420,
      fuel: 65,
      mp: 70,
      grp: 2,
      time: 130,
      cost: { steel: 2900000, alu: 1900000 },
      build: "works",
      spec: "base",
      w: { dmg: 2250, rof: 0.45, range: R_(10), pen: 50, speed: 900, kind: "shell", splash: 70 },
      role: "Heavy assault plate. Walks through whatever answers it.",
    },
    cyclone: {
      name: "Cyclone",
      short: "CYCL",
      cls: "soft",
      shape: "flak",
      hp: 1700,
      arm: 375,
      speed: 62,
      sight: 480,
      fuel: 50,
      mp: 35,
      grp: 4,
      time: 55,
      cost: { steel: 950000, alu: 300000 },
      build: "works",
      spec: "air",
      rm: 2,
      w: {
        dmg: 1000,
        rof: 2.2,
        range: R_(8),
        pen: 26,
        speed: 1250,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The mobile umbrella. Doubles its reach against the sky.",
    },
    talon: {
      name: "Talon I",
      short: "TLN1",
      cls: "arm",
      shape: "tank",
      big: true,
      hp: 3000,
      arm: 1500,
      speed: 48,
      sight: 420,
      fuel: 75,
      mp: 60,
      grp: 3,
      time: 85,
      cost: { steel: 1900000, alu: 650000 },
      build: "works",
      w: { dmg: 2500, rof: 0.5, range: R_(10), pen: 46, speed: 1000, kind: "shell", splash: 40 },
      role: "The first true heavy. Slow to build, slow to die.",
    },
    hornet: {
      name: "Hornet",
      short: "HNTT",
      cls: "arm",
      shape: "artillery",
      big: true,
      hp: 1800,
      arm: 150,
      speed: 50,
      sight: 430,
      fuel: 60,
      mp: 40,
      grp: 3,
      time: 65,
      cost: { steel: 950000, alu: 250000 },
      build: "works",
      rm: 2,
      noAA: true,
      w: {
        dmg: 1500,
        rof: 0.5,
        range: R_(10),
        pen: 36,
        speed: 640,
        kind: "rocket",
        splash: 70,
        arc: true,
      },
      role: "Rocket platform in heavy plate. No guns to the sky.",
    },
    longlance: {
      name: "Long Lance",
      short: "LLNC",
      cls: "soft",
      shape: "artillery",
      big: true,
      hp: 1500,
      arm: 37,
      speed: 46,
      sight: 440,
      fuel: 50,
      mp: 50,
      grp: 2,
      time: 95,
      cost: { steel: 975000, alu: 150000 },
      build: "works",
      spec: "base",
      rm: 3,
      w: {
        dmg: 14000,
        rof: 0.25,
        range: R_(7),
        pen: 44,
        speed: 600,
        kind: "shell",
        splash: 95,
        arc: true,
      },
      role: "The siege gun. Every shot is a doorway where a wall used to be.",
    },
    gambol: {
      name: "Gambol",
      short: "GMBl",
      cls: "arm",
      shape: "tank",
      hp: 2200,
      arm: 250,
      speed: 88,
      sight: 440,
      fuel: 75,
      mp: 40,
      grp: 4,
      time: 55,
      cost: { steel: 650000, alu: 650000 },
      build: "works",
      fast: true,
      w: { dmg: 2000, rof: 0.7, range: R_(9), pen: 38, speed: 1000, kind: "shell", splash: 38 },
      role: "The fast heavy. Arrives where the others were meant to.",
    },
    colossus: {
      name: "Colossus",
      short: "COLS",
      cls: "arm",
      shape: "tank",
      big: true,
      hp: 5200,
      arm: 3000,
      speed: 40,
      sight: 420,
      fuel: 110,
      mp: 120,
      grp: 1,
      time: 190,
      cost: { steel: 8900000, alu: 3900000 },
      build: "works",
      w: { dmg: 5000, rof: 0.4, range: R_(10), pen: 58, speed: 1000, kind: "shell", splash: 46 },
      role: "The Soviet super-heavy. There is one and a half of it, per base.",
    },
    talon2: {
      name: "Talon II",
      short: "TLN2",
      cls: "arm",
      shape: "tank",
      big: true,
      hp: 4600,
      arm: 4166,
      speed: 42,
      sight: 440,
      fuel: 100,
      mp: 110,
      grp: 1,
      time: 200,
      cost: { steel: 9500000, alu: 5500000 },
      build: "works",
      w: { dmg: 2500, rof: 0.4, range: R_(10), pen: 60, speed: 1000, kind: "shell", splash: 44 },
      role: "The second heavy. Thicker than the first, slower than the doubt.",
    },
    skyhawk: {
      name: "Skyhawk",
      short: "SKHW",
      cls: "soft",
      shape: "flak",
      hp: 1350,
      arm: 150,
      speed: 60,
      sight: 520,
      fuel: 50,
      mp: 30,
      grp: 4,
      time: 48,
      cost: { steel: 750000, alu: 175000 },
      build: "works",
      spec: "air",
      rm: 2,
      w: {
        dmg: 700,
        rof: 1.8,
        range: R_(8),
        pen: 24,
        speed: 1300,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "Long-sight plane-shooter. The sky's long arm against fighters.",
    },
    skyjaws: {
      name: "Skyjaws",
      short: "SKJW",
      cls: "soft",
      shape: "flak",
      hp: 1250,
      arm: 50,
      speed: 56,
      sight: 520,
      fuel: 40,
      mp: 35,
      grp: 3,
      time: 55,
      cost: { steel: 875000, alu: 225000 },
      build: "works",
      spec: "bigair",
      rm: 2,
      w: {
        dmg: 3000,
        rof: 1.4,
        range: R_(9),
        pen: 30,
        speed: 1300,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The heavy bomber's only friend to fear.",
    },
    rhino: {
      name: "Rhino",
      short: "RHNO",
      cls: "soft",
      shape: "td",
      hp: 1600,
      arm: 93,
      speed: 60,
      sight: 500,
      fuel: 40,
      mp: 35,
      grp: 4,
      time: 50,
      cost: { steel: 900000, alu: 300000 },
      build: "works",
      spec: "vehicle",
      rm: 2,
      w: { dmg: 650, rof: 0.9, range: R_(10), pen: 40, speed: 1500, kind: "bullet" },
      role: "The base guard. Park one at the gate; the tank column thinks it over.",
    },
    goliath: {
      name: "Goliath",
      short: "GLTH",
      cls: "soft",
      shape: "td",
      big: true,
      hp: 4200,
      arm: 4491,
      speed: 40,
      sight: 500,
      fuel: 90,
      mp: 100,
      grp: 1,
      time: 220,
      cost: { steel: 13900000, alu: 12900000 },
      build: "works",
      spec: "vehicle",
      rm: 2,
      w: { dmg: 675, rof: 0.7, range: R_(10), pen: 55, speed: 1500, kind: "bullet" },
      role: "The last tank destroyer. Nothing that moves gets close.",
    },
    railcrusher: {
      name: "Railcrusher",
      short: "RLCS",
      cls: "arm",
      shape: "tank",
      hp: 2100,
      arm: 500,
      speed: 50,
      sight: 420,
      fuel: 75,
      mp: 45,
      grp: 3,
      time: 70,
      cost: { steel: 950000, alu: 390000 },
      build: "works",
      spec: "train",
      w: { dmg: 2250, rof: 0.45, range: R_(10), pen: 44, speed: 1000, kind: "shell", splash: 50 },
      role: "Track insurance, on tracks.",
    },
    longsight: {
      name: "Longsight",
      short: "LNGS",
      cls: "soft",
      shape: "artillery",
      big: true,
      hp: 1400,
      arm: 50,
      speed: 44,
      sight: 460,
      fuel: 55,
      mp: 50,
      grp: 2,
      time: 100,
      cost: { steel: 1390000, alu: 590000 },
      build: "works",
      spec: "base",
      rm: 3,
      w: {
        dmg: 12500,
        rof: 0.22,
        range: R_(10),
        pen: 48,
        speed: 580,
        kind: "shell",
        splash: 95,
        arc: true,
      },
      role: "The long gun. Triples its reach at a base; the base is a small target.",
    },
    warlord: {
      name: "Warlord",
      short: "WRld",
      cls: "arm",
      shape: "tank",
      big: true,
      super: 1,
      hp: 7000,
      arm: 7500,
      speed: 30,
      sight: 420,
      fuel: 100,
      mp: 130,
      grp: 1,
      time: 240,
      cost: { steel: 9500000, alu: 4500000 },
      build: "heli",
      spec: "vehicle",
      rm: 2,
      rmMove: true,
      noTurret: true,
      w: { dmg: 1000, rof: 0.3, range: R_(10), pen: 62, speed: 1000, kind: "shell", splash: 46 },
      role: "Built at the rotor base. No turret: it stops, or it does not fire.",
    },
    behemoth: {
      name: "Behemoth",
      short: "BHMT",
      cls: "arm",
      shape: "tank",
      big: true,
      super: 1,
      hp: 6200,
      arm: 5000,
      speed: 28,
      sight: 430,
      fuel: 125,
      mp: 120,
      grp: 1,
      time: 240,
      cost: { steel: 11000000, alu: 3000000 },
      build: "heli",
      spec: "vehtrain",
      rm: 2,
      w: { dmg: 1500, rof: 0.35, range: R_(9), pen: 60, speed: 1000, kind: "shell", splash: 46 },
      role: "Built at the rotor base. A moving fortress that eats trains.",
    },
    siegeking: {
      name: "Siege King",
      short: "SGK",
      cls: "soft",
      shape: "artillery",
      big: true,
      super: 1,
      hp: 3200,
      arm: 750,
      speed: 24,
      sight: 440,
      fuel: 150,
      mp: 150,
      grp: 1,
      time: 300,
      cost: { steel: 9000000, alu: 8000000 },
      build: "heli",
      spec: "base",
      rm: 3,
      ammo: 6,
      ammoNeeds: "siegewagon",
      w: {
        dmg: 100000,
        rof: 0.15,
        range: R_(12),
        pen: 70,
        speed: 520,
        kind: "shell",
        splash: 120,
        arc: true,
      },
      role: "The monster howitzer. One round ends a district; the wagon feeds it.",
    },
    ammwagon: {
      name: "Ammo Wagon",
      short: "AMWG",
      cls: "soft",
      shape: "truck",
      hp: 900,
      arm: 18,
      speed: 66,
      sight: 330,
      fuel: 30,
      mp: 15,
      grp: 4,
      time: 40,
      cost: { steel: 750000, alu: 250000 },
      build: "works",
      unarmed: true,
      givesAmmo: true,
      role: "Feeds every gun that runs dry. Follow the line; stay behind it.",
    },
    siegewagon: {
      name: "Siege Wagon",
      short: "SGWG",
      cls: "soft",
      shape: "truck",
      hp: 1500,
      arm: 75,
      speed: 52,
      sight: 330,
      fuel: 50,
      mp: 25,
      grp: 2,
      time: 60,
      cost: { steel: 1500000, alu: 500000 },
      build: "works",
      unarmed: true,
      givesAmmo: true,
      role: "The heavy loader. Only it can feed the Siege King.",
    },
    polu: {
      name: "Gold Runner",
      short: "POLT",
      cls: "soft",
      shape: "truck",
      gold: true,
      hp: 620,
      arm: 10,
      speed: 60,
      sight: 350,
      fuel: 90,
      mp: 20,
      grp: 8,
      time: 45,
      cost: { steel: 75000, alu: 25000, fuel: 4500 },
      build: "works",
      homeOnly: true,
      polu: true,
      unarmed: true,
      role: "Burns resources to export gold. Ten a day, one gold. No queueing.",
    },

    /* ---------------- rotary wing ---------------- */
    kite: {
      name: "Kite",
      short: "KITE",
      cls: "air",
      shape: "heli",
      hp: 560,
      arm: 30,
      speed: 105,
      sight: 560,
      fuel: 125,
      mp: 20,
      grp: 8,
      time: 32,
      cost: { steel: 25000, alu: 225000 },
      build: "heli",
      alt: 40,
      w: { dmg: 500, rof: 1.2, range: R_(8), pen: 10, speed: 900, kind: "bullet" },
      role: "The cheap scout copter. See the map; do not fight it.",
    },
    rotor: {
      name: "Rotor",
      short: "RTOR",
      cls: "air",
      shape: "heli",
      hp: 900,
      arm: 150,
      speed: 95,
      sight: 520,
      fuel: 175,
      mp: 30,
      grp: 5,
      time: 50,
      cost: { steel: 100000, alu: 1250000 },
      build: "heli",
      alt: 44,
      spec: "vehicle",
      w: { dmg: 2000, rof: 0.8, range: R_(8), pen: 30, speed: 560, kind: "rocket", splash: 40 },
      role: "The copter that eats tanks. Anything with flak eats it back.",
    },
    skyhammer: {
      name: "Skyhammer",
      short: "SKHM",
      cls: "air",
      shape: "heli",
      hp: 1200,
      arm: 375,
      speed: 88,
      sight: 480,
      fuel: 225,
      mp: 35,
      grp: 5,
      time: 55,
      cost: { steel: 200000, alu: 1750000 },
      build: "heli",
      alt: 46,
      spec: "base",
      w: { dmg: 5500, rof: 0.5, range: R_(4), pen: 36, speed: 700, kind: "shell", splash: 80 },
      role: "The assault copter. Short reach, and the reach it has is fatal.",
    },
    dart: {
      name: "Dart",
      short: "DART",
      cls: "air",
      shape: "heli",
      hp: 780,
      arm: 75,
      speed: 110,
      sight: 540,
      fuel: 125,
      mp: 25,
      grp: 6,
      time: 45,
      cost: { steel: 95000, alu: 750000 },
      build: "heli",
      alt: 42,
      spec: "air",
      w: {
        dmg: 900,
        rof: 1.6,
        range: R_(10),
        pen: 20,
        speed: 1200,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The copter-killer. The sky's own weather.",
    },
    wraith: {
      name: "Wraith",
      short: "WRAI",
      cls: "air",
      shape: "heli",
      stealth: true,
      hp: 880,
      arm: 150,
      speed: 100,
      sight: 620,
      fuel: 275,
      mp: 30,
      grp: 4,
      time: 60,
      cost: { steel: 390000, alu: 2950000 },
      build: "heli",
      alt: 46,
      w: { dmg: 2500, rof: 0.8, range: R_(10), pen: 30, speed: 900, kind: "rocket", splash: 36 },
      role: "Invisible until seen by a detector. Your raid; their mystery.",
    },

    /* ---------------- fixed wing ---------------- */
    buzzard: {
      name: "Buzzard",
      short: "BZRD",
      cls: "air",
      shape: "plane",
      hp: 720,
      arm: 250,
      speed: 240,
      sight: 560,
      fuel: 150,
      mp: 30,
      grp: 6,
      time: 45,
      cost: { steel: 100000, alu: 750000 },
      build: "airfield",
      alt: 55,
      spec: "vehicle",
      w: { dmg: 600, rof: 1.2, range: R_(5), pen: 22, speed: 560, kind: "rocket", splash: 36 },
      role: "The ground-attack plane. Skims the tanks; flak skims it.",
    },
    longfin: {
      name: "Longfin",
      short: "LGFN",
      cls: "air",
      shape: "plane",
      hp: 1300,
      arm: 1000,
      speed: 190,
      sight: 520,
      fuel: 750,
      mp: 45,
      grp: 4,
      time: 70,
      cost: { steel: 450000, alu: 4500000 },
      build: "airfield",
      alt: 60,
      spec: "base",
      w: { dmg: 7500, rof: 0.4, range: R_(5), pen: 40, speed: 0, kind: "bomb", splash: 100 },
      role: "The base bomber. A base that flak-shoots it stops being a base.",
    },
    kestrel: {
      name: "Kestrel",
      short: "KSTL",
      cls: "air",
      shape: "plane",
      hp: 620,
      arm: 50,
      speed: 250,
      sight: 640,
      fuel: 150,
      mp: 15,
      grp: 8,
      time: 30,
      cost: { steel: 55000, alu: 125000 },
      build: "airfield",
      alt: 50,
      spec: "copter",
      w: { dmg: 100, rof: 2.0, range: R_(12), pen: 8, speed: 1500, kind: "bullet" },
      role: "The cheap long-sight scout. Sees the copters coming; outruns most of them.",
    },
    falcon: {
      name: "Falcon",
      short: "FALC",
      cls: "air",
      shape: "plane",
      hp: 950,
      arm: 375,
      speed: 270,
      sight: 580,
      fuel: 200,
      mp: 25,
      grp: 6,
      time: 48,
      cost: { steel: 250000, alu: 800000 },
      build: "airfield",
      alt: 58,
      spec: "air",
      w: {
        dmg: 500,
        rof: 2.4,
        range: R_(12),
        pen: 16,
        speed: 1600,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The dogfighter. Owns the sky and nothing under it.",
    },
    lightning: {
      name: "Lightning",
      short: "LGTN",
      cls: "air",
      shape: "plane",
      hp: 2400,
      arm: 3750,
      speed: 280,
      sight: 560,
      fuel: 550,
      mp: 60,
      grp: 3,
      time: 85,
      cost: { steel: 2500000, alu: 8500000 },
      build: "airfield",
      alt: 62,
      w: {
        dmg: 3000,
        rof: 1.0,
        range: R_(10),
        pen: 44,
        speed: 1500,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The heavy fighter. Arrives late and stays in the fight.",
    },
    nightjet: {
      name: "Nightjet",
      short: "NJET",
      cls: "air",
      shape: "jet",
      hp: 1300,
      arm: 750,
      speed: 320,
      sight: 600,
      fuel: 400,
      mp: 35,
      grp: 5,
      time: 65,
      cost: { steel: 750000, alu: 2900000 },
      build: "airfield",
      alt: 60,
      w: {
        dmg: 2500,
        rof: 2.0,
        range: R_(12),
        pen: 26,
        speed: 1600,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The jet. Fastest thing that carries a gun; the afterburner drinks the pool.",
    },
    skyfin: {
      name: "Skyfin",
      short: "SKFN",
      cls: "air",
      shape: "plane",
      hp: 1900,
      arm: 3000,
      speed: 200,
      sight: 520,
      fuel: 700,
      mp: 40,
      grp: 5,
      time: 75,
      cost: { steel: 750000, alu: 4500000 },
      build: "airfield",
      alt: 62,
      spec: "boat",
      w: { dmg: 5000, rof: 0.5, range: R_(6), pen: 38, speed: 0, kind: "bomb", splash: 90 },
      role: "The anti-ship bomber. A fleet it sights is already history.",
    },
    nightcrow: {
      name: "Nightcrow",
      short: "NCRW",
      cls: "air",
      shape: "plane",
      stealth: true,
      hp: 1100,
      arm: 375,
      speed: 220,
      sight: 560,
      fuel: 400,
      mp: 35,
      grp: 4,
      time: 70,
      cost: { steel: 900000, alu: 1900000 },
      build: "airfield",
      alt: 58,
      w: { dmg: 3000, rof: 0.7, range: R_(8), pen: 30, speed: 0, kind: "bomb", splash: 70 },
      role: "The stealth dive bomber. If their detector sees it, it is too late.",
    },
    warden: {
      name: "Warden",
      short: "WRDN",
      cls: "air",
      shape: "plane",
      detector: true,
      hp: 1500,
      arm: 2500,
      speed: 240,
      sight: 900,
      fuel: 800,
      mp: 30,
      grp: 5,
      time: 75,
      cost: { steel: 490000, alu: 4900000 },
      build: "airfield",
      alt: 58,
      w: {
        dmg: 900,
        rof: 1.4,
        range: R_(12),
        pen: 24,
        speed: 1500,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The detector plane. Sees the invisible and tells the base to fire.",
    },
    albatross: {
      name: "Albatross",
      short: "ALBT",
      cls: "air",
      shape: "plane",
      big: true,
      hp: 3400,
      arm: 3750,
      speed: 170,
      sight: 520,
      fuel: 900,
      mp: 80,
      grp: 2,
      time: 120,
      cost: { steel: 1990000, alu: 13900000 },
      build: "airfield",
      alt: 66,
      spec: "base",
      w: { dmg: 70000, rof: 0.12, range: R_(6), pen: 50, speed: 0, kind: "bomb", splash: 130 },
      role: "The heavy bomber. One bomb, one district. The fuel bill is a war.",
    },
    phantom: {
      name: "Phantom",
      short: "PHNT",
      cls: "air",
      shape: "plane",
      big: true,
      stealth: true,
      hp: 2600,
      arm: 2000,
      speed: 190,
      sight: 520,
      fuel: 2500,
      mp: 80,
      grp: 1,
      time: 140,
      cost: { steel: 1900000, alu: 19000000 },
      build: "airfield",
      alt: 64,
      spec: "base",
      w: { dmg: 90000, rof: 0.1, range: R_(6), pen: 50, speed: 0, kind: "bomb", splash: 130 },
      role: "The stealth siege bomber. The most expensive secret on the map.",
    },
    railfire: {
      name: "Railfire",
      short: "RLFR",
      cls: "air",
      shape: "plane",
      hp: 1000,
      arm: 500,
      speed: 200,
      sight: 500,
      fuel: 300,
      mp: 40,
      grp: 4,
      time: 65,
      cost: { steel: 220000, alu: 2200000 },
      build: "airfield",
      alt: 60,
      spec: "train",
      w: { dmg: 20000, rof: 0.3, range: R_(6), pen: 40, speed: 0, kind: "bomb", splash: 90 },
      role: "The train-killer plane. A locomotive that hears it is a ghost.",
    },
    tornade: {
      name: "Tornade",
      short: "TRND",
      cls: "air",
      shape: "plane",
      hp: 2100,
      arm: 3000,
      speed: 190,
      sight: 520,
      fuel: 300,
      mp: 50,
      grp: 3,
      time: 80,
      cost: { steel: 500000, alu: 3500000 },
      build: "airfield",
      alt: 62,
      spec: "vehicle",
      w: { dmg: 12500, rof: 0.25, range: R_(5), pen: 44, speed: 0, kind: "bomb", splash: 110 },
      role: "The tank column's end. Drops where the column is; the column was there.",
    },
    pioneer: {
      name: "Pioneer",
      short: "PNRR",
      cls: "air",
      shape: "plane",
      hp: 760,
      arm: 250,
      speed: 210,
      sight: 500,
      fuel: 175,
      mp: 20,
      grp: 6,
      time: 36,
      cost: { steel: 50000, alu: 300000 },
      build: "airfield",
      alt: 52,
      w: { dmg: 1000, rof: 1.0, range: R_(10), pen: 18, speed: 560, kind: "rocket", splash: 30 },
      role: "The cheap rocket plane. Thin, fast, and a hundred of them are a storm.",
    },

    /* ---------------- the water ---------------- */
    barge: {
      name: "Conquest Barge",
      short: "CBRG",
      cls: "sea",
      shape: "boat",
      hp: 620,
      arm: 15,
      speed: 80,
      sight: 380,
      fuel: 5,
      mp: 15,
      grp: 6,
      time: 12,
      cost: { steel: 35000, alu: 1000 },
      build: "shipyard",
      capture: true,
      unarmed: true,
      role: "Takes the naval ground. Escorts; it cannot fight.",
    },
    seawarden: {
      name: "Sea Warden",
      short: "SEWD",
      cls: "sea",
      shape: "ship",
      big: true,
      hp: 5200,
      arm: 7500,
      speed: 120,
      sight: 600,
      fuel: 45,
      mp: 90,
      grp: 2,
      time: 160,
      cost: { steel: 4500000, alu: 2500000 },
      build: "shipyard",
      spec: "vehicle",
      w: { dmg: 1500, rof: 0.5, range: R_(18), pen: 55, speed: 850, kind: "shell", splash: 54 },
      role: "The heavy patrol. The river, with an opinion about tanks.",
    },
    skyshore: {
      name: "Skyshore",
      short: "SKSH",
      cls: "sea",
      shape: "ship",
      hp: 2600,
      arm: 3000,
      speed: 110,
      sight: 560,
      fuel: 35,
      mp: 50,
      grp: 3,
      time: 90,
      cost: { steel: 1500000, alu: 350000 },
      build: "shipyard",
      spec: "air",
      w: {
        dmg: 300,
        rof: 2.4,
        range: R_(10),
        pen: 20,
        speed: 1250,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The shipboard flak. The sky over the water is its post.",
    },
    harborhammer: {
      name: "Harbor Hammer",
      short: "HBHM",
      cls: "sea",
      shape: "ship",
      big: true,
      hp: 8000,
      arm: 15000,
      speed: 95,
      sight: 560,
      fuel: 55,
      mp: 120,
      grp: 1,
      time: 260,
      cost: { steel: 19000000, alu: 2500000 },
      build: "shipyard",
      spec: "base",
      w: {
        dmg: 12000,
        rof: 0.2,
        range: R_(18),
        pen: 60,
        speed: 800,
        kind: "shell",
        splash: 110,
        arc: true,
      },
      role: "The siege ship. The coast is a long place; so is its reach.",
    },
    skiff: {
      name: "Skiff",
      short: "SKFF",
      cls: "sea",
      shape: "boat",
      hp: 480,
      arm: 10,
      speed: 135,
      sight: 420,
      fuel: 5,
      mp: 10,
      grp: 12,
      time: 12,
      cost: { steel: 45000, alu: 15000 },
      build: "shipyard",
      w: { dmg: 100, rof: 2.0, range: R_(12), pen: 8, speed: 1300, kind: "bullet" },
      role: "The fast boat. A dozen of them are a flotilla.",
    },
    stingray: {
      name: "Stingray",
      short: "STGY",
      cls: "sea",
      shape: "boat",
      hp: 1100,
      arm: 750,
      speed: 150,
      sight: 460,
      fuel: 15,
      mp: 30,
      grp: 5,
      time: 45,
      cost: { steel: 750000, alu: 150000 },
      build: "shipyard",
      spec: "boat",
      ammo: 8,
      w: { dmg: 1600, rof: 0.6, range: R_(12), pen: 44, speed: 380, kind: "torp", splash: 60 },
      role: "The torpedo boat. Runs on eight tubes and nerve.",
    },
    manta: {
      name: "Manta",
      short: "MNTA",
      cls: "sea",
      shape: "sub",
      stealth: true,
      hp: 3200,
      arm: 2500,
      speed: 105,
      sight: 480,
      fuel: 90,
      mp: 60,
      grp: 2,
      time: 130,
      cost: { steel: 3500000, alu: 1500000 },
      build: "shipyard",
      spec: "boat",
      rm: 2,
      ammo: 6,
      w: { dmg: 2000, rof: 0.4, range: R_(8), pen: 50, speed: 380, kind: "torp", splash: 60 },
      role: "The submarine. Invisible, patient, and ships only.",
    },
    destroyer: {
      name: "Destroyer",
      short: "DSTR",
      cls: "sea",
      shape: "ship",
      big: true,
      super: 1,
      hp: 9000,
      arm: 25000,
      speed: 130,
      sight: 640,
      fuel: 75,
      mp: 140,
      grp: 1,
      time: 320,
      cost: { steel: 35000000, alu: 9000000 },
      build: "shipyard",
      rm: 2,
      w: {
        dmg: 7500,
        rof: 0.4,
        range: R_(16),
        pen: 62,
        speed: 850,
        kind: "shell",
        splash: 80,
        arc: true,
      },
      w2: {
        dmg: 130,
        rof: 4.2,
        range: R_(10),
        pen: 20,
        speed: 1250,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The last of the fleet. Shore guns up front, flak up back, all of it plate.",
    },
    supplybarge: {
      name: "Supply Barge",
      short: "SUPB",
      cls: "sea",
      shape: "boat",
      hp: 1300,
      arm: 75,
      speed: 70,
      sight: 380,
      fuel: 35,
      mp: 20,
      grp: 3,
      time: 60,
      cost: { steel: 1250000, alu: 250000 },
      build: "shipyard",
      unarmed: true,
      givesAmmo: true,
      role: "Feeds the torpedo boats. Stays behind the line; the line is the idea.",
    },

    /* ---------------- the track ---------------- */
    loco: {
      name: "Loco",
      short: "LCO",
      cls: "arm",
      train: true,
      shape: "train",
      hp: 2600,
      arm: 750,
      speed: 130,
      sight: 480,
      fuel: 5,
      mp: 40,
      grp: 2,
      time: 50,
      cost: { steel: 390000, alu: 90000 },
      build: "trainyard",
      w: { dmg: 200, rof: 1.2, range: R_(8), pen: 10, speed: 1300, kind: "bullet" },
      role: "The engine. Runs the track; the track runs the war.",
    },
    railgun: {
      name: "Railgun",
      short: "RLGN",
      cls: "arm",
      train: true,
      shape: "train",
      hp: 3400,
      arm: 500,
      speed: 130,
      sight: 520,
      fuel: 10,
      mp: 50,
      grp: 2,
      time: 60,
      cost: { steel: 850000, alu: 150000 },
      build: "trainyard",
      spec: "vehicle",
      w: { dmg: 750, rof: 0.9, range: R_(18), pen: 34, speed: 1000, kind: "shell", splash: 40 },
      role: "The field gun on rails. Out-ranges the shore it stands beside.",
    },
    railstorm: {
      name: "Railstorm",
      short: "RLST",
      cls: "arm",
      train: true,
      shape: "train",
      big: true,
      hp: 4200,
      arm: 750,
      speed: 120,
      sight: 540,
      fuel: 25,
      mp: 80,
      grp: 1,
      time: 100,
      cost: { steel: 4500000, alu: 900000 },
      build: "trainyard",
      spec: "base",
      rm: 3,
      w: {
        dmg: 12000,
        rof: 0.2,
        range: R_(18),
        pen: 55,
        speed: 600,
        kind: "shell",
        splash: 110,
        arc: true,
      },
      role: "The howitzer on rails. Triple range at a base; the base is a small target.",
    },
    railflak: {
      name: "Railflak",
      short: "RLFK",
      cls: "arm",
      train: true,
      shape: "train",
      hp: 4600,
      arm: 3750,
      speed: 125,
      sight: 560,
      fuel: 20,
      mp: 60,
      grp: 1,
      time: 85,
      cost: { steel: 1950000, alu: 25000 },
      build: "trainyard",
      spec: "air",
      rm: 2,
      w: {
        dmg: 1500,
        rof: 2.0,
        range: R_(12),
        pen: 26,
        speed: 1300,
        kind: "bullet",
        aa: true,
        as: true,
      },
      role: "The flak on rails. The sky over the track has a name.",
    },
    railhunter: {
      name: "Railhunter",
      short: "RLHT",
      cls: "arm",
      train: true,
      shape: "train",
      hp: 4400,
      arm: 750,
      speed: 125,
      sight: 560,
      fuel: 20,
      mp: 70,
      grp: 1,
      time: 95,
      cost: { steel: 2200000, alu: 500000 },
      build: "trainyard",
      rm: 2,
      w: { dmg: 6000, rof: 0.5, range: R_(15), pen: 55, speed: 1500, kind: "bullet" },
      role: "The tank hunter on rails. The track is a long, straight line of kill.",
    },
    railviper: {
      name: "Railviper",
      short: "RLVP",
      cls: "arm",
      train: true,
      shape: "train",
      hp: 4800,
      arm: 3750,
      speed: 120,
      sight: 560,
      fuel: 15,
      mp: 70,
      grp: 1,
      time: 110,
      cost: { steel: 3900000, alu: 1900000 },
      build: "trainyard",
      spec: "boattrain",
      rm: 3,
      w: { dmg: 2500, rof: 0.7, range: R_(12), pen: 50, speed: 1000, kind: "shell", splash: 50 },
      role: "The river-and-track killer. Triple reach where the two meet.",
    },
  };
  for (const k in U) U[k].key = k;
  R.UDEF = U;
  R.UKEYS = Object.keys(U);

  // the menus of each production building, in the order they are offered
  R.PRODUCES = {
    works: [
      "apc",
      "stonehammer",
      "strider",
      "lynx",
      "sandblade",
      "runner",
      "mgmc",
      "sandpiper",
      "gnasher",
      "sheriff",
      "breaker1",
      "breaker2",
      "stinger",
      "mule",
      "railbreaker",
      "railcrusher",
      "rhino",
      "skyhawk",
      "skyjaws",
      "cyclone",
      "riverwolf",
      "volna",
      "hornet",
      "longlance",
      "gambol",
      "stormtitan",
      "bulwark",
      "talon",
      "talon2",
      "mauler",
      "huntress",
      "longsight",
      "colossus",
      "goliath",
      "ammwagon",
      "siegewagon",
      "polu",
    ],
    heli: ["warlord", "behemoth", "siegeking", "kite", "rotor", "skyhammer", "dart", "wraith"],
    airfield: [
      "kestrel",
      "falcon",
      "pioneer",
      "buzzard",
      "longfin",
      "nightjet",
      "skyfin",
      "nightcrow",
      "warden",
      "lightning",
      "railfire",
      "tornade",
      "albatross",
      "phantom",
    ],
    shipyard: [
      "barge",
      "skiff",
      "stingray",
      "skyshore",
      "supplybarge",
      "seawarden",
      "manta",
      "harborhammer",
      "destroyer",
    ],
    trainyard: ["loco", "railgun", "railflak", "railhunter", "railstorm", "railviper"],
  };

  // what the horde throws, if it is ever let loose (off by default)
  R.HORDE_UNITS = {
    zwalker: {
      name: "Walker",
      short: "ZWK",
      cls: "inf",
      shape: "zed",
      hp: 300,
      arm: 0,
      speed: 42,
      sight: 300,
      fuel: 0,
      mp: 0,
      grp: 10,
      time: 4,
      cost: {},
      w: { dmg: 20, rof: 1.2, range: 30, pen: 6, speed: 0, kind: "claw" },
    },
    zrunner: {
      name: "Runner",
      short: "ZRN",
      cls: "inf",
      shape: "zed",
      hp: 220,
      arm: 0,
      speed: 70,
      sight: 300,
      fuel: 0,
      mp: 0,
      grp: 10,
      time: 4,
      cost: {},
      w: { dmg: 16, rof: 1.4, range: 30, pen: 6, speed: 0, kind: "claw" },
    },
    zspitter: {
      name: "Spitter",
      short: "ZSP",
      cls: "inf",
      shape: "zed",
      hp: 260,
      arm: 0,
      speed: 38,
      sight: 320,
      fuel: 0,
      mp: 0,
      grp: 10,
      time: 4,
      cost: {},
      w: { dmg: 26, rof: 0.8, range: 190, pen: 8, speed: 520, kind: "rocket", splash: 44 },
    },
    zbrute: {
      name: "Brute",
      short: "ZBR",
      cls: "inf",
      shape: "zed",
      big: 1,
      hp: 1200,
      arm: 40,
      speed: 34,
      sight: 300,
      fuel: 0,
      mp: 0,
      grp: 4,
      time: 6,
      cost: {},
      w: { dmg: 62, rof: 0.85, range: 38, pen: 18, speed: 0, kind: "claw", splash: 30 },
    },
    zhulk: {
      name: "Hulk",
      short: "ZHL",
      cls: "inf",
      shape: "zed",
      big: 1,
      hp: 3000,
      arm: 90,
      speed: 26,
      sight: 320,
      fuel: 0,
      mp: 0,
      grp: 2,
      time: 9,
      cost: {},
      w: { dmg: 140, rof: 0.7, range: 44, pen: 30, speed: 0, kind: "claw", splash: 34 },
    },
  };
  for (const k in R.HORDE_UNITS) {
    R.HORDE_UNITS[k].key = k;
    U[k] = R.HORDE_UNITS[k];
  }
  R.HORDE = {
    startAfter: 210,
    waveEvery: 165,
    growth: 0.14,
    mix: [
      { key: "zwalker", w: 10, min: 0 },
      { key: "zrunner", w: 5, min: 1 },
      { key: "zspitter", w: 3, min: 2 },
      { key: "zbrute", w: 3, min: 3 },
      { key: "zhulk", w: 1.2, min: 6 },
    ],
    nests: 3,
  };

  /* =======================================================================
     BUILDINGS
     cat  econ | mil | def | sup | cmd
     maxL factory levels; the cmd buildings are bought in gold
     ep   energy points a level (or a standing) costs
     ======================================================================= */

  const B = {
    hq: {
      name: "Command Centre",
      short: "HQ",
      cat: "core",
      size: 4,
      hp: 7000,
      arm: 60,
      cost: { concrete: 250000, steel: 120000, alu: 40000 },
      time: 90,
      max: 1,
      hard: true,
      sight: 520,
      mp: 40,
      desc: "The heart of it. Lose this and the company is finished.",
    },
    concrete: {
      name: "Concrete Plant",
      short: "CP",
      cat: "econ",
      size: 3,
      hp: 2600,
      arm: 24,
      cost: { concrete: 20000, steel: 5000 },
      time: 30,
      max: 16,
      makes: "concrete",
      rate: 3750,
      ep: 5,
      desc: "Pours concrete and raises the concrete store.",
    },
    steel: {
      name: "Steelworks",
      short: "SW",
      cat: "econ",
      size: 3,
      hp: 2800,
      arm: 28,
      cost: { concrete: 30000, steel: 8000 },
      time: 42,
      max: 16,
      makes: "steel",
      rate: 2500,
      ep: 7,
      desc: "Steel, and a bigger steel store. The heart of the industry.",
    },
    alu: {
      name: "Aluminium Works",
      short: "AW",
      cat: "econ",
      size: 3,
      hp: 2700,
      arm: 26,
      cost: { concrete: 40000, steel: 20000, alu: 6000 },
      time: 52,
      max: 16,
      makes: "alu",
      rate: 1500,
      ep: 9,
      desc: "Aircraft need aluminium. So do the heavier tanks.",
    },
    oil: {
      name: "Oil Refinery",
      short: "OR",
      cat: "econ",
      size: 3,
      hp: 2600,
      arm: 24,
      cost: { concrete: 36000, steel: 16000 },
      time: 46,
      max: 15,
      makes: "fuel",
      rate: 6250,
      onOil: 2.2,
      ep: 11,
      desc: "Fuel for the pool and for the road. On a seep it pays more than double.",
    },

    works: {
      name: "Vehicle Works",
      short: "VW",
      cat: "mil",
      size: 4,
      hp: 3400,
      arm: 36,
      cost: { concrete: 60000, steel: 30000, alu: 8000 },
      time: 58,
      max: 4,
      site: ["home", "tank"],
      desc: "Builds everything with tracks. Needs a home or tank base.",
    },
    airfield: {
      name: "Airfield",
      short: "AF",
      cat: "mil",
      size: 4,
      hp: 3200,
      arm: 32,
      cost: { concrete: 90000, steel: 40000, alu: 60000 },
      time: 68,
      max: 3,
      site: ["air"],
      desc: "Fixed wing. Needs an air base.",
    },
    heli: {
      name: "Rotor Pad",
      short: "RP",
      cat: "mil",
      size: 4,
      hp: 3100,
      arm: 32,
      cost: { concrete: 80000, steel: 35000, alu: 70000 },
      time: 64,
      max: 3,
      site: ["copter"],
      desc: "Rotary wing — and, as if there are no rules, the three heaviest vehicles on the map.",
    },
    shipyard: {
      name: "Shipyard",
      short: "SY",
      cat: "mil",
      size: 3,
      hp: 3000,
      arm: 32,
      cost: { concrete: 70000, steel: 26000 },
      time: 52,
      max: 3,
      site: ["naval"],
      water: true,
      desc: "Must sit on water, on a naval base. Builds everything that floats.",
    },
    trainyard: {
      name: "Railyard",
      short: "RY",
      cat: "mil",
      size: 4,
      hp: 3200,
      arm: 34,
      cost: { concrete: 80000, steel: 45000 },
      time: 56,
      max: 3,
      site: ["train"],
      rail: true,
      desc: "Armoured trains, on the track only. Needs a rail base.",
    },

    flak: {
      name: "Flak",
      short: "FLK",
      cat: "def",
      size: 1,
      hp: 900,
      arm: 12,
      cost: { concrete: 8000, steel: 12000 },
      time: 12,
      max: 80,
      ep: 9,
      flak: 1,
      hard: true,
      startFlak: true,
      turret: 1,
      w: {
        dmg: 15,
        rof: 4.4,
        range: R_(9),
        pen: 12,
        speed: 1250,
        kind: "bullet",
        aa: true,
        as: true,
      },
      desc: "Base defence. Ground and air; boats and trains are easier to see. Upgrade it to plate (L2) and long gun (L3) in gold.",
    },
    mg: {
      name: "Machine Gun Nest",
      short: "MG",
      cat: "def",
      size: 2,
      hp: 1500,
      arm: 40,
      cost: { concrete: 16000, steel: 11000 },
      time: 19,
      max: 60,
      turret: 1,
      w: { dmg: 7, rof: 6.5, range: R_(6), pen: 6, speed: 1600, kind: "bullet" },
      desc: "Long burst, infantry only. Pairs with an anti-tank gun.",
    },
    atgun: {
      name: "Anti-Tank Gun",
      short: "AT",
      cat: "def",
      size: 2,
      hp: 1600,
      arm: 44,
      cost: { concrete: 19000, steel: 19000 },
      time: 25,
      max: 60,
      turret: 1,
      w: { dmg: 62, rof: 0.5, range: R_(7), pen: 30, speed: 420, kind: "rocket" },
      desc: "The cheap answer to armour, bolted down.",
    },
    howitzer: {
      name: "Howitzer Pit",
      short: "HOW",
      cat: "def",
      size: 2,
      hp: 1450,
      arm: 32,
      cost: { concrete: 30000, steel: 29000 },
      time: 35,
      max: 40,
      turret: 1,
      indirect: true,
      w: {
        dmg: 132,
        rof: 0.27,
        range: R_(16),
        pen: 30,
        speed: 620,
        kind: "shell",
        splash: 92,
        arc: true,
      },
      desc: "Outranges a mobile gun by a little, costs less than a tank.",
    },
    wall: {
      name: "Wall",
      short: "WL",
      cat: "def",
      size: 1,
      hp: 2200,
      arm: 44,
      cost: { concrete: 1500 },
      time: 6,
      max: 400,
      wall: true,
      inert: true, // part of the base itself: not clickable, never a target
      desc: "The base wall. One piece of the arch — it is not built, it comes with the ground, and no gun bothers it.",
    },
    gate: {
      name: "Gate",
      short: "GT",
      cat: "def",
      size: 1,
      hp: 1900,
      arm: 40,
      cost: { concrete: 2000, steel: 800 },
      time: 8,
      max: 40,
      wall: true,
      gate: true,
      inert: true, // the door opens when the flaks fall; it is never shot
      desc: "The way in. It opens for its own side, and for everybody else only once the base's flaks are down.",
    },

    crane: {
      name: "Repair Crane",
      short: "RRC",
      cat: "sup",
      size: 3,
      hp: 1800,
      arm: 28,
      cost: { gold: 79 },
      goldCost: [79, 159, 349],
      time: 30,
      max: 3,
      goldBld: true,
      recover: false,
      desc: "L1 mends ground; L2 mends faster; L3 mends the air, 2% a minute. Non-recoverable.",
    },
    sight: {
      name: "Sight Tower",
      short: "SIT",
      cat: "sup",
      size: 2,
      hp: 1300,
      arm: 22,
      cost: { gold: 9 },
      goldCost: [9, 29, 99],
      time: 26,
      max: 3,
      goldBld: true,
      recover: false,
      sight: 1100,
      desc: "Reveals the ground around the base in three levels. Non-recoverable.",
    },
    jammer: {
      name: "Jammer Tower",
      short: "JAM",
      cat: "sup",
      size: 2,
      hp: 1300,
      arm: 22,
      cost: { gold: 19 },
      goldCost: [19, 49, 99],
      time: 26,
      max: 3,
      goldBld: true,
      recover: false,
      desc: "Hides the base and its armies from the enemy's sight, in three levels. Non-recoverable.",
    },
    detector: {
      name: "Detector Tower",
      short: "DTC",
      cat: "sup",
      size: 2,
      hp: 1400,
      arm: 26,
      cost: { gold: 29 },
      goldCost: [29],
      time: 28,
      max: 2,
      goldBld: true,
      recover: false,
      desc: "Sees the invisible: stealth planes, copters and subs. Non-recoverable.",
    },

    maxpower: {
      name: "Power Plant",
      short: "PP",
      cat: "cmd",
      size: 2,
      hp: 1200,
      arm: 18,
      cost: { gold: 19 },
      goldCost: [19],
      time: 22,
      max: 15,
      goldBld: true,
      recover: 1,
      effect: { ep: 100 },
      desc: "+100 Energy Points. Fifteen per company; one gold to recover after a fall.",
    },
    maxmil: {
      name: "Military Central",
      short: "MC",
      cat: "cmd",
      size: 2,
      hp: 1300,
      arm: 20,
      cost: { gold: 29 },
      goldCost: [29],
      time: 24,
      max: 15,
      goldBld: true,
      recover: 1,
      effect: { mp: 100 },
      desc: "+100 Military Points. Fifteen per company; one gold to recover after a fall.",
    },
    maxoffice: {
      name: "Military Office",
      short: "MO",
      cat: "cmd",
      size: 2,
      hp: 1400,
      arm: 22,
      cost: { gold: 19 },
      goldCost: [19, 29, 59, 109],
      time: 26,
      max: 4,
      goldBld: true,
      recover: false,
      effect: { mp: 500 },
      desc: "+500 Military Points. Four per company; the price rises with each. Not recoverable.",
    },
    maxcommand: {
      name: "Command Base",
      short: "CB",
      cat: "cmd",
      size: 2,
      hp: 1300,
      arm: 20,
      cost: { gold: 69 },
      goldCost: [69],
      time: 24,
      max: 3,
      goldBld: true,
      recover: 1,
      effect: { base: 1 },
      desc: "+1 base to the cap. Three per company; one gold to recover after a fall.",
    },
    maxextend: {
      name: "Base Extension",
      short: "BX",
      cat: "cmd",
      size: 2,
      hp: 1200,
      arm: 18,
      cost: { gold: 49 },
      goldCost: [49],
      time: 22,
      max: 1, // per settlement
      goldBld: true,
      recover: 9,
      perSite: true,
      effect: { extend: 1 },
      desc: "Unlocks factory levels 13 to 16 for this settlement. One per base; nine gold to recover.",
    },
    maxgroup: {
      name: "Group Extension",
      short: "GX",
      cat: "cmd",
      size: 2,
      hp: 1200,
      arm: 18,
      cost: { gold: 39 },
      goldCost: [39, 69, 159],
      time: 24,
      max: 3,
      goldBld: true,
      recover: false,
      effect: { group: 1 },
      desc: "+1 squad to the group limit. Three per company. Not recoverable.",
    },
  };
  for (const k in B) B[k].key = k;
  R.BDEF = B;
  R.BKEYS = Object.keys(B);

  /* ---------- the shape of a base wall ----------
     The Desert Order bases do not draw squares: the wall is an arch —
     a square whose corners have been pulled round. A superellipse
     (|x/a|^n + |y/a|^n = 1, n a little over 3) is that shape: roomy
     like the square it replaced, rounded like the screenshots. `v`
     under 1 is inside the wall, the band around 1 is the wall itself. */
  R.WALL_N = 3.5;
  R.wallRing = function (dx, dy, a) {
    const nx = Math.abs(dx) / a,
      ny = Math.abs(dy) / a;
    return Math.pow(nx, R.WALL_N) + Math.pow(ny, R.WALL_N);
  };

  /* ---------- the ground a base stands on ----------
     The arch, the gate and the flak arc are drawn before they are
     built, and every piece has to land exactly where it was drawn —
     so the disc under the base is cleared and packed first. Water is
     left alone (a naval base keeps its shore) and so are the rail and
     any oil seep under the yard. */
  R.clearBaseGround = function (t, cx, cy, rad) {
    for (let dy = -rad; dy <= rad; dy++)
      for (let dx = -rad; dx <= rad; dx++) {
        if (dx * dx + dy * dy > rad * rad) continue;
        const i = t.idx(cx + dx, cy + dy);
        if (i < 0) continue;
        const v = t.type[i];
        if (v === R.T.WATER || v === R.T.OIL || v === R.T.RAIL) continue;
        t.type[i] = R.T.FIRM;
      }
    t.version++;
  };

  // the build menu, in the order it is drawn
  R.BUILD_MENU = [
    { key: "econ", name: "Industry", keys: ["concrete", "steel", "alu", "oil"] },
    { key: "mil", name: "Military", keys: ["works", "airfield", "heli", "shipyard", "trainyard"] },
    { key: "def", name: "Defence", keys: ["flak", "mg", "atgun", "howitzer"] },
    {
      key: "cmd",
      name: "Command",
      keys: [
        "crane",
        "sight",
        "jammer",
        "detector",
        "maxpower",
        "maxmil",
        "maxoffice",
        "maxcommand",
        "maxextend",
        "maxgroup",
      ],
    },
  ];

  // what a flak level costs and buys (the two gold upgrades)
  R.FLAK_ARMOR_GOLD = 29; // L2: plate, ~ten times the soak
  R.FLAK_WEAPON_GOLD = 99; // L3: the long gun
  R.FLAK_RECOVER = 9; // what each comes back for, after a fall
  R.FLAK_UP_RANGE = R_(13); // the L3 gun's reach
  R.FLAK_SEA_RANGE_BONUS = R_(6); // boats and trains read large from a tower

  /* =======================================================================
     THE GOLD SHOP
     What the purse buys, what it costs, what comes back for one gold
     after a base falls. `place: true` means it is a building you site on
     your own ground; the rest are entries in the ledger.
     ======================================================================= */

  R.GOLD_SHOP = [
    {
      key: "maxpower",
      name: "Power Plant",
      desc: "+100 Energy Points",
      max: 15,
      place: "maxpower",
      recover: 1,
    },
    {
      key: "maxmil",
      name: "Military Central",
      desc: "+100 Military Points",
      max: 15,
      place: "maxmil",
      recover: 1,
    },
    {
      key: "maxoffice",
      name: "Military Office",
      desc: "+500 Military Points",
      max: 4,
      place: "maxoffice",
      recover: false,
    },
    {
      key: "maxcommand",
      name: "Command Base",
      desc: "+1 base to the cap",
      max: 3,
      place: "maxcommand",
      recover: 1,
    },
    {
      key: "maxextend",
      name: "Base Extension",
      desc: "Factory levels 13–16 on this settlement",
      max: 1,
      place: "maxextend",
      recover: 9,
      perSite: true,
    },
    {
      key: "maxgroup",
      name: "Group Extension",
      desc: "+1 squad to the group limit",
      max: 3,
      place: "maxgroup",
      recover: false,
    },
    {
      key: "crane",
      name: "Repair Crane",
      desc: "Mends units parked at the base",
      max: 3,
      place: "crane",
      recover: false,
    },
    {
      key: "sight",
      name: "Sight Tower",
      desc: "Reveals the ground around the base",
      max: 3,
      place: "sight",
      recover: false,
    },
    {
      key: "jammer",
      name: "Jammer Tower",
      desc: "Hides the base and its armies from sight",
      max: 3,
      place: "jammer",
      recover: false,
    },
    {
      key: "detector",
      name: "Detector Tower",
      desc: "Sees stealth units; the base fires them",
      max: 2,
      place: "detector",
      recover: false,
    },
  ];

  // the non-placeable gold purchases, straight from the ledger
  R.GOLD_LEDGER = [
    {
      key: "flakArmor",
      name: "Flak Plate (L2)",
      cost: 29,
      desc: "Plate a flak: ~ten times the soak. Needs no enemy near, and a standing flak.",
    },
    {
      key: "flakWeapon",
      name: "Flak Long Gun (L3)",
      cost: 99,
      desc: "A long-range double-barrel. Needs L2 first, and no enemy near.",
    },
    {
      key: "instant",
      name: "Immediate Resources",
      cost: 49,
      desc: "+30 million of concrete, steel and aluminium. Only while each is under 10 million.",
    },
    {
      key: "accel1",
      name: "Acceleration · 1 hour",
      cost: 15,
      desc: "Triple production for an hour.",
      hours: 1,
    },
    {
      key: "accel4",
      name: "Acceleration · 4 hours",
      cost: 40,
      desc: "Triple production for four hours.",
      hours: 4,
    },
    {
      key: "accel12",
      name: "Acceleration · 12 hours",
      cost: 90,
      desc: "Triple production for twelve hours.",
      hours: 12,
    },
  ];

  // an acceleration hour, in game seconds
  R.ACCEL_HOUR = 120;
  // the free faucets: one hour of steel a day on the home ground (under 1M
  // steel), and one hour of aluminium once a second base is held
  R.FREE_ACCEL_MAX = 1000000;
  // the polu faucet: ten Gold Runners in one game day, one gold
  R.POLU_PER_DAY = 10;
  R.GOLD_PER_POLU_DAY = 1;
  // the sand blade quota: fifty a day at a tenth of the price
  R.QUOTA_PER_DAY = 50;

  /* =======================================================================
     NATION PERSONALITIES
     How an AI nation plays: what it builds, what it attacks with, and how
     quickly it comes for you. The mixes name the real roster now.
     ======================================================================= */

  R.PERSONA = {
    rusher: {
      name: "Blitz",
      eco: 0.55,
      army: 1.35,
      air: 0.4,
      sea: 0.3,
      aggro: 1.0,
      first: 150,
      wave: 105,
      mix: [
        ["strider", 5],
        ["stonehammer", 4],
        ["sandblade", 3],
        ["mgmc", 2],
        ["rhino", 2],
        ["sheriff", 2],
      ],
    },
    boomer: {
      name: "Industry",
      eco: 1.5,
      army: 0.85,
      air: 0.7,
      sea: 0.5,
      aggro: 0.35,
      first: 420,
      wave: 175,
      mix: [
        ["sheriff", 4],
        ["talon", 3],
        ["breaker2", 3],
        ["cyclone", 2],
        ["rhino", 2],
        ["longlance", 1],
      ],
    },
    airpower: {
      name: "Air Force",
      eco: 0.95,
      army: 0.7,
      air: 1.8,
      sea: 0.4,
      aggro: 0.7,
      first: 300,
      wave: 140,
      mix: [
        ["falcon", 3],
        ["buzzard", 3],
        ["longfin", 2],
        ["rotor", 2],
        ["skyjaws", 2],
        ["cyclone", 2],
      ],
    },
    navy: {
      name: "Naval",
      eco: 1.0,
      army: 0.75,
      air: 0.5,
      sea: 2.0,
      aggro: 0.6,
      first: 340,
      wave: 155,
      mix: [
        ["skiff", 4],
        ["stingray", 3],
        ["skyshore", 2],
        ["seawarden", 2],
        ["strider", 3],
        ["sandpiper", 2],
      ],
    },
    turtler: {
      name: "Fortress",
      eco: 1.15,
      army: 0.7,
      air: 0.6,
      sea: 0.5,
      aggro: 0.25,
      first: 520,
      wave: 220,
      mix: [
        ["sheriff", 4],
        ["talon", 3],
        ["rhino", 3],
        ["breaker2", 2],
        ["skyjaws", 2],
      ],
      turret: 2.2,
    },
    spread: {
      name: "Expansionist",
      eco: 1.1,
      army: 1.0,
      air: 0.8,
      sea: 0.7,
      aggro: 0.55,
      first: 250,
      wave: 125,
      mix: [
        ["strider", 4],
        ["stonehammer", 4],
        ["sandblade", 3],
        ["lynx", 3],
        ["mgmc", 2],
        ["rotor", 2],
      ],
      expand: 2.0,
    },
  };

  // who plays what
  R.NATION_SETUP = {
    1: { persona: "rusher", name: "Iron Pact" },
    2: { persona: "boomer", name: "Azure League" },
    3: { persona: "spread", name: "Sand Union" },
    4: { persona: "airpower", name: "Crimson Front" },
    5: { persona: "navy", name: "Jade Accord" },
  };

  /* =======================================================================
     STARTER QUESTS
     The four the tutorial teaches, each paying a little when it is done.
     ======================================================================= */

  R.QUESTS = [
    { key: "q_breda", name: "Raise three Stonehammers", reward: { concrete: 60000, steel: 60000 } },
    { key: "q_flak", name: "Break an enemy flak", reward: { steel: 80000 } },
    {
      key: "q_site",
      name: "Take a settlement with a Conquest Truck",
      reward: { gold: 5, steel: 100000 },
    },
  ];

  /* =======================================================================
     FACTORY LEVELS
     What a level of a plant buys: more room, more output, more plate.
     Levels 13 and up only exist once the settlement has an extension.
     ======================================================================= */

  R.MAXLEVEL = 16;
  R.MAXLEVEL_DEF = 3;

  // how high a building of this kind may be taken, at this settlement
  R.maxLevelOf = function (def, site) {
    if (def.makes) {
      const ext = site && site.extend;
      return ext ? R.LVL_MAX[def.makes] || 16 : R.LVL_BASE;
    }
    return 1; // everything else stands at one level
  };

  R.levelHp = function (def, lvl) {
    return Math.round(def.hp * Math.pow(R.LVL_HP_MUL, (lvl || 1) - 1));
  };

  // what the level of a plant pours out per minute, before productivity
  R.levelRate = function (def, lvl) {
    return def.rate ? def.rate * Math.pow(R.LVL_RATE_MUL, (lvl || 1) - 1) : 0;
  };

  // the price of the NEXT level: level n+1 costs n's price grown a little
  R.upCost = function (def, lvl) {
    const m = Math.pow(R.LVL_COST_MUL, (lvl || 1) - 1);
    const c = {};
    for (const k in def.cost) if (k !== "gold") c[k] = Math.round(def.cost[k] * m);
    return c;
  };
  R.upTime = function (def, lvl) {
    return def.time * Math.pow(R.LVL_TIME_MUL, lvl || 1);
  };
  // the energy a single level of a plant costs
  R.epOfLevel = function (def, _lvl) {
    return def.makes ? R.EP_PER_LVL[def.makes] || 5 : 0;
  };

  /* =======================================================================
     FLAK LEVELS
     A flak is a level-one building. Two global gold upgrades lift every
     flak the company still owns: plate (L2), then the long gun (L3).
     ======================================================================= */

  R.flakStats = function (l2, l3) {
    let hp = 900,
      arm = 12,
      dmg = 15,
      rof = 4.4,
      range = R_(9),
      pen = 12;
    if (l2) {
      hp = 2400;
      arm = 120;
      pen = 20;
    }
    if (l3) {
      hp = 3400;
      arm = 220;
      dmg = 26;
      pen = 30;
      range = R.FLAK_UP_RANGE;
    }
    return { hp, arm, dmg, rof, range, pen };
  };
})();
